"""add hnsw index on embeddings

Revision ID: 7db0b8b18db3
Revises: a3050fad676a
Create Date: 2026-10-03 20:07:19.676629

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (needed by autogenerated Vector columns)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7db0b8b18db3"
down_revision: str | Sequence[str] | None = "a3050fad676a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_faq_items_embedding_hnsw",
        "faq_items",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_faq_items_embedding_hnsw",
        table_name="faq_items",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###
