"""add collection and content hash

Revision ID: c7f4fa1e000c
Revises: 7db0b8b18db3
Create Date: 2026-10-03 22:24:20.251288

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (needed by autogenerated Vector columns)
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7f4fa1e000c"
down_revision: str | Sequence[str] | None = "7db0b8b18db3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "faq_items",
        sa.Column("collection", sa.String(length=50), server_default="default", nullable=False),
    )
    op.add_column("faq_items", sa.Column("content_hash", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("faq_items", "content_hash")
    op.drop_column("faq_items", "collection")
    # ### end Alembic commands ###
